import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CommonConst } from './(common)/_constants';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: CommonConst.APP_TITLE,
  description: 'Generated by abe',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
