import { Box, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { CommonConst } from './(common)/_constants';
import { AuthProvider } from './_components';
import '@mantine/core/styles.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: CommonConst.APP_TITLE,
  description: 'Generated by abe',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <MantineProvider>
          <AuthProvider>
            <Box
              style={{
                height: '96dvh',
                width: '100vw',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              {children}
            </Box>
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
